### ISSUE TITLE
[Potential Bug]: Cardinal API Missing After Install w/ Modrinth

### ISSUE THREAD

**Issue by ant0n-0x0000** [BondiBen/minecraft-modpacks#15]
### Contact Details

ant0n

### What happened?

I installed the latest version of the pack via Modrinth (Release 1.5.1) and it failed to launch since Cardinal API was not included in the pack. I just unlocked it and added it myself and it worked fine afterwards, I'm only opening this issue so you're aware that other people could be experiencing the same problem.

No custom install was used, literally just clicked "install" and Cardinal was missing. I tried to repair the install too via Modrinth and it still didn't add Cardinal.

I'm unable to attach the full crash logs to this comment since it's too long, so I'll just include the header of it. Reach out to me on discord if you need the rest :)

### Version

Create-Extra (Default)

### Relevant log output

```shell
---- Quilt Loader: Failed to load ----
Date/Time: 2024/01/22 14:13:47.4133
Quilt Loader Version: 0.23.1

-- Error 1 --

Traveler's Backpack requires any version of cardinal-components-base, which is missing!

- <mods>/travelers-backpack-1.20.1-9.1.9.jar


-- Error 2 --

Traveler's Backpack requires any version of cardinal-components-entity, which is missing!

- <mods>/travelers-backpack-1.20.1-9.1.9.jar


-- Plugin State --

Cycle number = 1
Cycle Step = SOLVE

Loaded Plugins (2):
 - 'quilt_loader' (Builtin)
 - 'quilted_fabric_loader' (Builtin)
```

**Comment by GideonWhite1029** [comment]
I found out that Cardinal components is present in mrpack and it is listed as added. But as soon as I install the build (I use PrismLauncher) then he doesn't count it and it doesn't download. Most likely, this is a bug of the launcher itself, but just in case, I'll check the work in the other launchers.

**Comment by GideonWhite1029** [comment]
The problem turned out to be in the launcher, I made mrpack in another place and all the dependencies are now present. @ant0n-0x0000 thanks again for the feedback.
